Repository canonical/manager.assets.ubuntu.com, pull requests merged in 2019-11, with the labels that each got.

#67 Improve the asset card layout
  package.json
  static/sass/main.scss
  templates/_asset-list.html
  templates/_asset.html
  templates/_layout.html
  templates/created.html
  templates/index.html
  templates/update.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#69 Load copy link JS for all pages
  templates/_layout.html
  templates/create.html
  templates/created.html
  templates/index.html
  templates/update.html
Labels: Review: Code +1

#68 Add Python testing infrastructure
  .circleci/config.yml
  package.json
  run
  tests/__init__.py
  tests/test_routes.py
Labels: Review: Code needed, Review: QA needed
